- name: "Apache installation using Docker"
  hosts: prod
  become: true
  vars_files:
    - files/secrets/credentials.yml
  pre_tasks:
    - name: "Install system utilities"
      package: name='{{ item }}' state=present update_cache=yes
      when: ansible_distribution == "CentOS"
      loop:
        - epel-release
        - git
        - python-pip
        - wget
    - name: "Install Python libraries for Docker"
      pip: name=docker-py
  tasks:
    - name: "Copy website file template"
      template:
        src: index.html.j2
        dest: /home/admin/index.html
    - name: "Create Apache Container"
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        volumes:
          - /home/admin/index.html:/usr/local/apache2/htdocs/index.html
