- hosts: prod
  become: true
  vars:
    system_user: admin
  vars_files:
    - files/secrets/credentials.yml
  pre_tasks:
    - name: "Add www-data Linux user"
      user: name=www-data state=present
  roles:
    - { role: ansible-role-containerized-wordpress }
